### PR TITLE
fix(import-script): improves taskmodel importing functionality

### PR DESCRIPTION
**Pull request by eve-horne**
# Changes introduced
Importing task models now uses Cf Associations as logic
## Related issue(s):
CSE-390
## Contributor checklist

- [ ] Wrote/updated tests for introduced changes
- [ ] ~~Added new stories for created/modified components (if applicable)~~
- [ ] Updated Postman library for created/modified routes (if applicable)
- [x] Verified that there are no issues in CircleCI
- [x] Assigned yourself to the PR
- [x] Removed `WIP:` from the PR title
- [x] Requested review from the SB Reviewers team

## Reviewer checklist

- [ ] Assigned yourself to the PR
- [ ] Read through the changes in the `Files changed` tab
- [ ] Verified that tests were written/modified
- [ ] ~~Verified that stories were written/modified (if applicable)~~
- [ ] Verified that Postman was updated (if applicable)
- [ ] Checked out the branch and tested changes locally

### CODE REVIEW

**Review by danvanhorn — DISMISSED** [review]
We are getting more task models now, which is good, however we are not getting any examples at all now

**Review by tnoelcke — DISMISSED** [review]
This will return every example in each task model. Meaning that for math grade 3 claim 1 target A, I will get 19 examples in each task model. Where as i should have 6 in 1a 3 in 1b 1c and 2a and then 4 in 2b. Please, improve this code so that it relates the correct example to each task model.

**Review by tnoelcke — APPROVED** [review]
Looks good! I'm now getting the correct number of examples.

**Pull request merged**
