### PR TITLE
Add pull request template

### PR DESCRIPTION
**Pull request by puregarlic**
# Changes introduced

This PR removes Markdown formatting from `lint-staged`, and adds the template demoed here.

## Related issue(s):

- CSE-194
- CSE-236

## Contributor checklist

- [ ] Wrote/updated tests for introduced changes
- [ ] ~~Added new stories for created/modified components (if applicable)~~
- [ ] Updated Postman library for created/modified routes (if applicable)
- [x] Verified that there are no issues in CircleCI
- [x] Assigned yourself to the PR
- [x] Removed `WIP:` from the PR title
- [x] Requested review from the SB Reviewers team

## Reviewer checklist

- [ ] Assigned yourself to the PR
- [ ] Read through the changes in the `Files changed` tab
- [ ] Verified that tests were written/modified
- [ ] ~~Verified that stories were written/modified (if applicable)~~
- [ ] Verified that Postman was updated (if applicable)
- [ ] Checked out the branch and tested changes locally

### CODE REVIEW

**Comment by puregarlic** [comment]
I need to rebase this to `dev` before it can be merged.

**Comment by puregarlic** [comment]
TIL about interactive rebasing. This PR is ready for review.

**Review by tnoelcke — APPROVED** [review]

**Pull request merged**
