### PR TITLE
Feat/CSE 276 create an endpoint for targets

### PR DESCRIPTION
**Pull request by danvanhorn**
# Changes introduced

Added an endpoint that returns targets based on `subject`, `grades`, `claim`, and `targetShortCode`.  This route is tested, and works under the assumption that it will not be called without one of the parameters. I also added the postman library that I had generated.

## Related issue(s):

- CSE-275
- CSE-276
- CSE-222

## Contributor checklist

- [x] Wrote/updated tests for introduced changes
- [ ] ~~Added new stories for created/modified components (if applicable)~~
- [x] Updated Postman library for created/modified routes (if applicable)
- [x] Verified that there are no issues in CircleCI
- [x] Assigned yourself to the PR
- [x] Removed `WIP:` from the PR title
- [x] Requested review from the SB Reviewers team

## Reviewer checklist

- [x] Assigned yourself to the PR
- [ ] Read through the changes in the `Files changed` tab
- [x] Verified that tests were written/modified
- [ ] ~~Verified that stories were written/modified (if applicable)~~
- [x] Verified that Postman was updated (if applicable)
- [x] Checked out the branch and tested changes locally

### CODE REVIEW

**Review by puregarlic — CHANGES_REQUESTED** [review]
The changes themselves look good, but it seems like your computer isn't running git hooks correctly, or the configuration I wrote doesn't work correctly on Windows. Add the following script to the NPM scripts section:

```json
{
  "format": "prettier --single-quote --print-width 100 --write src/**/*.ts",
}
``` 

Run the script:

```sh
npm run format
```

And then commit the results. This way, you'll have the script for formatting your code in the short term, until I can further debug your configuration.

**Comment by danvanhorn** [comment]
I updated the npm scripts to include `format` as suggested by @puregarlic.

**Pull request merged**
