### PR TITLE
Feat/cse 260 implement logging strategy

### PR DESCRIPTION
**Pull request by danvanhorn**
# Changes introduced

Added Jaeger tracing and the three docker containers: `jaeger-agent`, `jaeger-collector`, and `jaeger-query` to run it locally. We're using the winston logger that can communicate with or logstash instance. The `tracer` and `logger` instances are available to each `Response` passed through the middleware and request handlers. and Both the tracer and I wrote tests for each of the new modules I added.

## Related issue(s):

- CSE-259
- CSE-260

## Contributor checklist

- [x] Wrote/updated tests for introduced changes
- [ ] ~~Added new stories for created/modified components (if applicable)~~
- [ ] ~~Updated Postman library for created/modified routes (if applicable)~~
- [x] Verified that there are no issues in CircleCI
- [x] Assigned yourself to the PR
- [x] Removed `WIP:` from the PR title
- [x] Requested review from the SB Reviewers team

## Reviewer checklist

- [x] Assigned yourself to the PR
- [x] Read through the changes in the `Files changed` tab
- [x] Verified that tests were written/modified
- [ ] ~~Verified that stories were written/modified (if applicable)~~
- [ ] Verified that Postman was updated (if applicable)
- [ ] Checked out the branch and tested changes locally

### CODE REVIEW

**Comment by tnoelcke** [comment]
When I try to run this I get this error:
```sh
jaeger-agent        | {"level":"error","ts":1536781923.9062283,"caller":"peerlistmgr/peer_list_mgr.go:171","msg":"Unable
to connect","host:port":"jaeger-collector:14267","connCheckTimeout":0.25,"error":"tchannel error ErrCodeTimeout: timeout","stacktrace":"github.com/jaegertracing/jaeger/pkg/discovery/peerlistmgr.(*PeerListManager).ensureConnections\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/pkg/discovery/peerlistmgr/peer_list_mgr.go:171\ngithub.com/jaegertracing/jaeger/pkg/discovery/peerlistmgr.(*PeerListManager).maintainConnections\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/pkg/discovery/peerlistmgr/peer_list_mgr.go:101"}
```

Is there some steps I'm missing or something special I need to install?

**Comment by danvanhorn** [comment]
@tnoelcke, the containers all start at the same time because we don't have this thing running in minikube yet. If you want a little bit then they all connect to each other in a minute or two. The `jaeger-collector` and `jaeger-query` images will output similar errors until that time.

**Review by tnoelcke — APPROVED** [review]
Nice work keeping the code coverage up. Seems like you've had to do some cleaver mocking to make that possible. Nice work!

**Pull request merged**
